### ISSUE TITLE
align comments based on previous/next lines

### ISSUE THREAD

**Issue by millermedeiros** [millermedeiros/rocambole-indent#1]
Expected:
```js
try {
  bla();
// comment
} catch(e) {
  throw e;
}

switch(foo) {
  case bar:
    baz();
    // falls through

  case biz:
    what();
}
```
Wrong:
```js
try {
  bla();
  // comment
} catch (e) {
  throw e;
}

switch(foo) {
  case bar:
    baz();
  // falls through

  case biz:
    what();
}
```

maybe expose a new method that aligns comments inside a node and/or make it part of the `sanitize` method.

see https://github.com/millermedeiros/esformatter/issues/270 and https://github.com/millermedeiros/esformatter/issues/209

**Comment by jzaefferer** [comment]
I'd like to use this login in my plugin to replace [my method for updating comments](https://github.com/jzaefferer/esformatter-jquery-chain/blob/75e9f178eb0a68223ccdfcf6fef7fe74d5f0557d/plugin.js#L87-L96). The `nested` argument is the indent level, which shouldn't be needed anymore. I only look at comments within the given node, since that's what got changed elsewhere.

So once implemented here, it could be exposed as a method similar to the `line` method (btw. that's a poor name, since it sounds like you set the indent, not in/decrease it).

**Comment by millermedeiros** [comment]
I renamed the `line` method to `addLevel` and will work on the align function soon.

**Comment by jzaefferer** [comment]
:+1:

**Comment by jzaefferer** [comment]
I just tested `alignComments(node)` on my esformatter-jquery-chain plugin, seems to work well (my tests all pass). Nice work!
